
modLoader="javafml"
loaderVersion="[26,)" #mandatory (26 is current forge version)

issueTrackerURL="http://my.issue.tracker/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="anothergemsmod" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Another Gems Mod" #mandatory

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/FredHappyface/Minecraft.AnotherGemsMod" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="anothergemsmod.png" #optional
#credits="" #optional
authors="FredHappyface" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Release for 1.14.3. This mod includes some world gen, gems with various properties and recipes for various tools and armour. Adds some decoration blocks that can be crafted from the gems too, such as a block of gem, stairs, slabs, and bricks This is a first stab at a Minecraft mod and the main purpose is to become acquainted with the modding framework. '''



#[[dependencies.examplemod]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.14.3]"
#    ordering="NONE"
#    side="BOTH"